### ISSUE TITLE
[NEWCMD] unified webash.sh commands

### ISSUE THREAD

**Issue by ghost** [taokann/WeBash#5]
## The idea

As indicated in title, combine the scripts `start.sh` and `stop.sh` may be a good idea. In effect, the two *Bash* scrips have similarities. For the host user, command like `webash` may be more simple to use.

## How I see this

For sure, it can create more complexity. The console command syntax can become 
```
webash [GENERAL_ARG [GENERAL_ARG]] COMMAND [SPECIFIC_ARG [SPECIFIC_ARG]]
```
 where the general argument `GENERAL_ARG` can be `--help` or `--verbose`, where `COMMAND` can be the command `start` or `stop` and where `SPECIFIC_ARG` can be `--port`, `--name` or other specific argument.

----------------

## L'idée

Comme indiqué dans le titre, les scripts `start.sh` et `stop.sh` peuvent être une bonne idée. En effet, les deux scripts *Bash* sont similaires. Pour l'utilisateur hôte, une commande comme `webash` serait plus simple à utiliser.

## Comment je vois ça

Bien sûr, ça peut créer plus de complexité. La syntaxe de la commande de console peut devenir
```
webash [GENERAL_ARG [GENERAL_ARG]] COMMAND [SPECIFIC_ARG [SPECIFIC_ARG]]
```
 où l'argument général `GENERAL_ARG` peut être `--help` ou `--verbose`, où `COMMAND` peut être la commande `start` ou `stop` et où  `SPECIFIC_ARG` serait `--port`, `--name` ou autre argument spécifique.

**Comment by taokann** [comment]
@Alnotz Those two files are now merged into ``weba.sh``. Thanks!
